### ISSUE TITLE
Typescript

### ISSUE THREAD

**Issue by M4urici0GM** [Summer-andy/react-loading#45]
I'm having trouble with using the lib with typescript.
It seems the lib doesn't have the  declaration file for module 'react-loadingg'.
Will it have support?

**Comment by sixiaodong123** [comment]
Thank you for your support. I will include this issue in my update plan.

**Comment by Summer-andy** [comment]
i will start in   @https://github.com/Summer-andy/react-loading-typescript. If you have free time, welcome to build together！ @M4urici0GM

**Comment by M4urici0GM** [comment]
I'll try help in my free time, don't worry 😃

**Comment by Summer-andy** [comment]
Hello, I have completed the initial upgrade of the project.  you can install ``` react-loadingg@1.7.4-alpha.1 ``` in you project.  If you have any questions during use, please contact me again, thanks!

**Comment by Summer-andy** [comment]
Hello, I have completed the initial upgrade of the project.  You can install  the ``` react-loadingg@1.7.4-alpha.1 ``` in you project.  If you have any questions during use, please contact me again, thanks!  @M4urici0GM
